### ISSUE TITLE
Massive amount of lag in public lobbies

### ISSUE THREAD

**Issue by Cyanide719** [ColossusYTTV/ColossalCheatMenuV2#2]
I have a 3060 gpu and somehow with the new update to the menu im getting 4 frames

**Comment by Cyanide719** [comment]
This only happens in public servers and generally when in a server with other people. I tried the mod menu update from 3 weeks ago(the last update) although it didn't work i was getting a solid 60 fps

**Comment by ColossusYTTV** [comment]
yea I know lmaooooo its caused by a 404 error when getting the MOTD, you can just remove it if you want its in Update() in plugin.cs. I also fixed it aswell as some other things so I will be releasing that soon as probably what will be the last update

**Comment by Cyanide719** [comment]
Awesome!
